---
- name: Installing PHP8.1
  apt: name=software-properties-common state=present

- name: Repo PHP 8.1
  apt_repository: repo="ppa:ondrej/php"

- name: Install PHP
  apt: name=php8.1 state=latest update_cache=yes

- name: Installing PHP8.1 and It's Dependencies
  apt:
    name: "{{item}}"
    state: present
    update_cache: true
  loop:
      - php
      - libapache2-mod-php
      - php8.1-mysql
      - php8.1-common
      - php8.1-xml
      - php8.1-xmlrpc
      - php8.1-curl
      - php8.1-gd
      - php8.1-imagick
      - php8.1-cli
      - php8.1-dev
      - php8.1-imap
      - php8.1-mbstring
      - php8.1-opcache
      - php8.1-soap
      - php8.1-zip
      - php8.1-intl
      
  become: yes
